# Gonneville project parameters
#File locations
source_dir: /Users/lin236/Library/CloudStorage/OneDrive-CSIRO/Minerals4D/Projects/Gonneville/Composite/
working_dir: /Users/lin236/Library/CloudStorage/OneDrive-CSIRO/Minerals4D/Projects/Gonneville/DK_shap_outputs/
roi_dir: /Users/lin236/Library/CloudStorage/OneDrive-CSIRO/Minerals4D/Projects/Gonneville/ROI/

#Features
response: Pd_ppm
covariates: [Pt_ppm, Ni_ppm, Co_ppm, Cr_ppm, Cu_ppm, Lith1_Code]
cov_labels: ['X (m)', 'Y (m)', 'Z (m)', 'Pt (ppm)', 'Ni (ppm)', 'Co (ppm)', 'Cr (ppm)', 'Lithology 1 code']

#Coordinates
x: mid_x_y
y: mid_y_y
z: mid_z_y

#model
layers: [200, 100, 100]
dropout: [0.2, 0.5, 0.5]
activation: relu
loss: poisson
optimizer: adam
learning_rate: 0.001
batch_size: 32
epochs: 100
cellsize: 400


